export type IntegrationStatus = "ready" | "enterprise";

export type IntegrationCategory =
  | "CRM"
  | "Automation"
  | "Calendar"
  | "Communication"
  | "E-commerce"
  | "Helpdesk"
  | "Productivity"
  | "SMS"
  | "Telephony"
  | "WhatsApp"
  | "Payments"
  | "Email"
  | "Databases"
  | "Finance"
  | "Healthcare"
  | "Analytics";

export type Integration = {
  id: string;
  name: string;
  description: string;
  category: IntegrationCategory;
  status: IntegrationStatus;
  /** Hex used for the letter mark */
  color: string;
  mark?: string;
};

export const integrationCategories: IntegrationCategory[] = [
  "CRM",
  "Automation",
  "Calendar",
  "Communication",
  "E-commerce",
  "Helpdesk",
  "Productivity",
  "SMS",
  "Telephony",
  "WhatsApp",
  "Payments",
  "Email",
  "Databases",
  "Finance",
  "Healthcare",
  "Analytics",
];

export const integrations: Integration[] = [
  // CRM
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Push dispositions, transcripts, and recordings onto the lead.",
    category: "CRM",
    status: "ready",
    color: "#00A1E0",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Log every outbound call outcome back to the contact timeline.",
    category: "CRM",
    status: "ready",
    color: "#FF7A59",
  },
  {
    id: "zoho-crm",
    name: "Zoho CRM",
    description: "Sync call notes and next steps for Indian sales teams.",
    category: "CRM",
    status: "ready",
    color: "#E42527",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "Update deal stages automatically after each voice attempt.",
    category: "CRM",
    status: "ready",
    color: "#017737",
  },
  {
    id: "leadsquared",
    name: "LeadSquared",
    description: "Trigger SvaraCall from lead score and capture call outcomes.",
    category: "CRM",
    status: "ready",
    color: "#F15A29",
  },
  {
    id: "freshsales",
    name: "Freshsales",
    description: "Keep Freshworks CRM records current after every dial.",
    category: "CRM",
    status: "ready",
    color: "#CF4B3A",
  },
  {
    id: "copper",
    name: "Copper",
    description: "Google Workspace–friendly CRM sync for call dispositions.",
    category: "CRM",
    status: "ready",
    color: "#F15A29",
    mark: "Cu",
  },
  {
    id: "kylas",
    name: "Kylas",
    description: "India-first CRM sync for SMB outbound teams.",
    category: "CRM",
    status: "ready",
    color: "#5B5FEF",
  },
  {
    id: "close",
    name: "Close CRM",
    description: "Built for calling teams — mirror outcomes into Close.",
    category: "CRM",
    status: "ready",
    color: "#1A73E8",
  },
  {
    id: "bitrix24",
    name: "Bitrix24",
    description: "Write call activity into Bitrix deals and contacts.",
    category: "CRM",
    status: "ready",
    color: "#2FC6F6",
  },
  {
    id: "dynamics",
    name: "Microsoft Dynamics 365",
    description: "Enterprise CRM path with tenant admin consent.",
    category: "CRM",
    status: "enterprise",
    color: "#002050",
    mark: "D365",
  },
  {
    id: "gohighlevel",
    name: "GoHighLevel",
    description: "Agency CRM sync — marketplace path for multi-tenant.",
    category: "CRM",
    status: "enterprise",
    color: "#00B2FF",
    mark: "GHL",
  },

  // Automation
  {
    id: "zapier",
    name: "Zapier",
    description: "Trigger dials from any Zap — or fire next steps mid-call.",
    category: "Automation",
    status: "ready",
    color: "#FF4A00",
  },
  {
    id: "make",
    name: "Make",
    description: "Orchestrate multi-step voice workflows without code.",
    category: "Automation",
    status: "ready",
    color: "#6D00CC",
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Self-host or cloud — webhook into SvaraCall pipelines.",
    category: "Automation",
    status: "ready",
    color: "#EA4B71",
  },
  {
    id: "pabbly",
    name: "Pabbly Connect",
    description: "Affordable automation for Indian growth teams.",
    category: "Automation",
    status: "ready",
    color: "#FF6B35",
  },
  {
    id: "integrately",
    name: "Integrately",
    description: "One-click recipes that start outbound voice runs.",
    category: "Automation",
    status: "ready",
    color: "#6366F1",
  },
  {
    id: "workato",
    name: "Workato",
    description: "Enterprise iPaaS path for complex stack orchestration.",
    category: "Automation",
    status: "enterprise",
    color: "#FF5C35",
  },

  // Calendar
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Book slots live on the call against open calendars.",
    category: "Calendar",
    status: "enterprise",
    color: "#4285F4",
    mark: "GCal",
  },
  {
    id: "calendly",
    name: "Calendly",
    description: "Confirm and reschedule appointments during the call.",
    category: "Calendar",
    status: "ready",
    color: "#006BFF",
  },
  {
    id: "calcom",
    name: "Cal.com",
    description: "Open-source scheduling synced to voice bookings.",
    category: "Calendar",
    status: "ready",
    color: "#111111",
    mark: "Cal",
  },
  {
    id: "outlook-calendar",
    name: "Outlook Calendar",
    description: "Microsoft Graph calendar booking for enterprise tenants.",
    category: "Calendar",
    status: "enterprise",
    color: "#0078D4",
    mark: "OL",
  },
  {
    id: "zoho-calendar",
    name: "Zoho Calendar",
    description: "Schedule follow-ups in Zoho while the call is live.",
    category: "Calendar",
    status: "ready",
    color: "#E42527",
    mark: "ZC",
  },

  // Communication
  {
    id: "slack",
    name: "Slack",
    description: "Alert sales or ops the moment a call converts.",
    category: "Communication",
    status: "ready",
    color: "#4A154B",
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    description: "Enterprise chat alerts with Graph consent.",
    category: "Communication",
    status: "enterprise",
    color: "#6264A7",
    mark: "Teams",
  },
  {
    id: "telegram",
    name: "Telegram",
    description: "Bot alerts for campaign status and escalations.",
    category: "Communication",
    status: "ready",
    color: "#26A5E4",
  },
  {
    id: "discord",
    name: "Discord",
    description: "Push campaign digests into community ops channels.",
    category: "Communication",
    status: "ready",
    color: "#5865F2",
  },

  // E-commerce
  {
    id: "shopify",
    name: "Shopify",
    description: "COD verify, order confirm, and RTO reduction calls.",
    category: "E-commerce",
    status: "ready",
    color: "#96BF48",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    description: "Sync order events into outbound confirmation flows.",
    category: "E-commerce",
    status: "ready",
    color: "#96588A",
    mark: "Woo",
  },
  {
    id: "magento",
    name: "Magento",
    description: "Adobe Commerce order and delivery voice workflows.",
    category: "E-commerce",
    status: "ready",
    color: "#F26322",
  },
  {
    id: "unicommerce",
    name: "Unicommerce",
    description: "India OMS triggers for shipping and COD calls.",
    category: "E-commerce",
    status: "ready",
    color: "#FF6B00",
    mark: "Uni",
  },
  {
    id: "easyecom",
    name: "EasyEcom",
    description: "Multi-channel order events → voice confirmations.",
    category: "E-commerce",
    status: "ready",
    color: "#00A3E0",
    mark: "EE",
  },
  {
    id: "bigcommerce",
    name: "BigCommerce",
    description: "Storefront events that start post-purchase dials.",
    category: "E-commerce",
    status: "ready",
    color: "#121118",
    mark: "BC",
  },
  {
    id: "wix",
    name: "Wix Stores",
    description: "App Market path for multi-merchant storefronts.",
    category: "E-commerce",
    status: "enterprise",
    color: "#0C6EFC",
  },

  // Helpdesk
  {
    id: "zendesk",
    name: "Zendesk",
    description: "Open tickets with full call context attached.",
    category: "Helpdesk",
    status: "ready",
    color: "#03363D",
  },
  {
    id: "freshdesk",
    name: "Freshdesk",
    description: "Create tickets from failed deliveries or escalations.",
    category: "Helpdesk",
    status: "ready",
    color: "#25C16F",
  },
  {
    id: "intercom",
    name: "Intercom",
    description: "Hand off voice outcomes into Intercom conversations.",
    category: "Helpdesk",
    status: "ready",
    color: "#6AFDEF",
  },
  {
    id: "zoho-desk",
    name: "Zoho Desk",
    description: "Indian support desks get call transcripts automatically.",
    category: "Helpdesk",
    status: "ready",
    color: "#E42527",
    mark: "ZD",
  },
  {
    id: "helpscout",
    name: "Help Scout",
    description: "Shared inbox updates after every customer call.",
    category: "Helpdesk",
    status: "ready",
    color: "#1292EE",
  },
  {
    id: "servicenow",
    name: "ServiceNow",
    description: "Enterprise ITSM path with scoped admin access.",
    category: "Helpdesk",
    status: "enterprise",
    color: "#81B5A1",
    mark: "SN",
  },

  // Productivity
  {
    id: "notion",
    name: "Notion",
    description: "Log call summaries into the workspace your ops uses.",
    category: "Productivity",
    status: "ready",
    color: "#000000",
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Sheet-like ops boards updated from live call data.",
    category: "Productivity",
    status: "ready",
    color: "#18BFFF",
  },
  {
    id: "asana",
    name: "Asana",
    description: "Create follow-up tasks when a call needs a human.",
    category: "Productivity",
    status: "ready",
    color: "#F06A6A",
  },
  {
    id: "clickup",
    name: "ClickUp",
    description: "Push outcomes into ClickUp lists and automations.",
    category: "Productivity",
    status: "ready",
    color: "#7B68EE",
  },
  {
    id: "monday",
    name: "Monday.com",
    description: "Board updates for campaign status and escalations.",
    category: "Productivity",
    status: "ready",
    color: "#FF3D57",
  },
  {
    id: "trello",
    name: "Trello",
    description: "Move cards when a voice workflow completes.",
    category: "Productivity",
    status: "ready",
    color: "#0052CC",
  },
  {
    id: "jira",
    name: "Jira",
    description: "File issues from voice escalations with full context.",
    category: "Productivity",
    status: "ready",
    color: "#0052CC",
  },
  {
    id: "google-sheets",
    name: "Google Sheets",
    description: "Start from a simple sheet upload — still the fastest path.",
    category: "Productivity",
    status: "ready",
    color: "#0F9D58",
    mark: "Sheets",
  },

  // SMS
  {
    id: "twilio-sms",
    name: "Twilio SMS",
    description: "OTP, reminders, and SMS fallback after missed calls.",
    category: "SMS",
    status: "ready",
    color: "#F22F46",
    mark: "Tw",
  },
  {
    id: "msg91",
    name: "MSG91",
    description: "India DLT-ready SMS alongside voice campaigns.",
    category: "SMS",
    status: "enterprise",
    color: "#1A73E8",
  },
  {
    id: "gupshup-sms",
    name: "Gupshup SMS",
    description: "High-volume India SMS with template registration.",
    category: "SMS",
    status: "enterprise",
    color: "#FF6B35",
    mark: "GS",
  },
  {
    id: "plivo-sms",
    name: "Plivo SMS",
    description: "API SMS for confirmations and recovery nudges.",
    category: "SMS",
    status: "ready",
    color: "#0A2540",
  },
  {
    id: "kaleyra",
    name: "Kaleyra",
    description: "India CPaaS messaging tied to outbound voice.",
    category: "SMS",
    status: "enterprise",
    color: "#00B2A9",
  },

  // Telephony
  {
    id: "exotel",
    name: "Exotel",
    description: "India cloud telephony with business verification.",
    category: "Telephony",
    status: "enterprise",
    color: "#FF5A00",
  },
  {
    id: "twilio-voice",
    name: "Twilio Voice",
    description: "SIP / REST trunks for international and multi-region.",
    category: "Telephony",
    status: "ready",
    color: "#F22F46",
    mark: "TV",
  },
  {
    id: "plivo-voice",
    name: "Plivo Voice",
    description: "Bring your trunk or buy numbers via Plivo SIP.",
    category: "Telephony",
    status: "ready",
    color: "#0A2540",
    mark: "PV",
  },
  {
    id: "telnyx",
    name: "Telnyx",
    description: "Carrier-grade SIP for high-volume outbound.",
    category: "Telephony",
    status: "ready",
    color: "#00C08B",
  },
  {
    id: "airtel-sip",
    name: "Airtel SIP",
    description: "Carrier trunks provisioned via business agreement.",
    category: "Telephony",
    status: "enterprise",
    color: "#E40000",
    mark: "Air",
  },
  {
    id: "knowlarity",
    name: "Knowlarity",
    description: "India cloud telephony partner path.",
    category: "Telephony",
    status: "enterprise",
    color: "#FF6600",
    mark: "Kn",
  },

  // WhatsApp
  {
    id: "wati",
    name: "WATI",
    description: "WhatsApp BSP with Meta verification for follow-ups.",
    category: "WhatsApp",
    status: "enterprise",
    color: "#00A884",
  },
  {
    id: "interakt",
    name: "Interakt",
    description: "India WhatsApp journeys after or instead of a call.",
    category: "WhatsApp",
    status: "enterprise",
    color: "#25D366",
  },
  {
    id: "gupshup-wa",
    name: "Gupshup WhatsApp",
    description: "BSP path with template approval for production.",
    category: "WhatsApp",
    status: "enterprise",
    color: "#FF6B35",
    mark: "GW",
  },
  {
    id: "aisensy",
    name: "AiSensy",
    description: "WhatsApp automation paired with voice recovery.",
    category: "WhatsApp",
    status: "enterprise",
    color: "#7C3AED",
  },
  {
    id: "meta-cloud",
    name: "Meta Cloud API",
    description: "Direct WhatsApp Business — needs Meta verification.",
    category: "WhatsApp",
    status: "enterprise",
    color: "#0084FF",
    mark: "Meta",
  },

  // Payments
  {
    id: "razorpay",
    name: "Razorpay",
    description: "Payment links and collection nudges after the call.",
    category: "Payments",
    status: "enterprise",
    color: "#072654",
  },
  {
    id: "cashfree",
    name: "Cashfree",
    description: "India PA rails for collections and refunds voice flows.",
    category: "Payments",
    status: "enterprise",
    color: "#1A73E8",
  },
  {
    id: "payu",
    name: "PayU",
    description: "Merchant KYC path for payment follow-up calls.",
    category: "Payments",
    status: "enterprise",
    color: "#4A90D9",
  },
  {
    id: "phonepe",
    name: "PhonePe",
    description: "Direct merchant agreement for collection workflows.",
    category: "Payments",
    status: "enterprise",
    color: "#5F259F",
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Test mode fast; live KYC for production money movement.",
    category: "Payments",
    status: "enterprise",
    color: "#635BFF",
  },

  // Email
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "Email receipts and confirmations after voice outcomes.",
    category: "Email",
    status: "ready",
    color: "#1A82E2",
  },
  {
    id: "mailgun",
    name: "Mailgun",
    description: "Transactional email triggered from call events.",
    category: "Email",
    status: "ready",
    color: "#F06B66",
  },
  {
    id: "resend",
    name: "Resend",
    description: "Developer-friendly email from campaign webhooks.",
    category: "Email",
    status: "ready",
    color: "#000000",
  },
  {
    id: "ses",
    name: "Amazon SES",
    description: "Production sending after AWS sandbox approval.",
    category: "Email",
    status: "enterprise",
    color: "#FF9900",
    mark: "SES",
  },
  {
    id: "gmail",
    name: "Gmail",
    description: "Mailbox scopes need Google verification for production.",
    category: "Email",
    status: "enterprise",
    color: "#EA4335",
  },

  // Databases
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Write structured call data into your product DB.",
    category: "Databases",
    status: "ready",
    color: "#336791",
    mark: "PG",
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "Native driver sync for legacy and modern stacks.",
    category: "Databases",
    status: "ready",
    color: "#4479A1",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description: "Document store for transcripts and event payloads.",
    category: "Databases",
    status: "ready",
    color: "#47A248",
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "PostgREST + webhooks for modern app backends.",
    category: "Databases",
    status: "ready",
    color: "#3ECF8E",
  },
  {
    id: "firebase",
    name: "Firebase",
    description: "Realtime updates for campaign dashboards.",
    category: "Databases",
    status: "ready",
    color: "#FFCA28",
  },
  {
    id: "redis",
    name: "Redis",
    description: "Queue and cache for high-throughput dial campaigns.",
    category: "Databases",
    status: "ready",
    color: "#DC382D",
  },

  // Finance
  {
    id: "zoho-books",
    name: "Zoho Books",
    description: "Tie collections outcomes to invoices without re-keying.",
    category: "Finance",
    status: "ready",
    color: "#E42527",
    mark: "ZB",
  },
  {
    id: "tally",
    name: "Tally",
    description: "Desktop/XML path for Indian accounting stacks.",
    category: "Finance",
    status: "enterprise",
    color: "#1B4F9C",
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    description: "Sandbox fast; Intuit reviews production apps.",
    category: "Finance",
    status: "enterprise",
    color: "#2CA01C",
    mark: "QB",
  },
  {
    id: "xero",
    name: "Xero",
    description: "App Store review for multi-customer finance sync.",
    category: "Finance",
    status: "enterprise",
    color: "#13B5EA",
  },

  // Healthcare
  {
    id: "practo",
    name: "Practo",
    description: "Clinic partnership path for appointment reminders.",
    category: "Healthcare",
    status: "enterprise",
    color: "#28328C",
  },
  {
    id: "healthplix",
    name: "HealthPlix",
    description: "EMR partner path for Indian clinics.",
    category: "Healthcare",
    status: "enterprise",
    color: "#00A3A1",
    mark: "HP",
  },
  {
    id: "epic",
    name: "Epic EHR",
    description: "Formal certification before patient-data production.",
    category: "Healthcare",
    status: "enterprise",
    color: "#C41230",
  },
  {
    id: "drchrono",
    name: "DrChrono",
    description: "Sandbox available; production needs vendor approval.",
    category: "Healthcare",
    status: "enterprise",
    color: "#00AEEF",
    mark: "DC",
  },

  // Analytics
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Push call outcomes into product analytics.",
    category: "Analytics",
    status: "ready",
    color: "#7856FF",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    description: "Conversation metrics in your product funnel.",
    category: "Analytics",
    status: "ready",
    color: "#1D24CA",
  },
  {
    id: "posthog",
    name: "PostHog",
    description: "Open-source product analytics for voice events.",
    category: "Analytics",
    status: "ready",
    color: "#F54E00",
  },
  {
    id: "ga4",
    name: "Google Analytics",
    description: "GA4 events for campaign attribution.",
    category: "Analytics",
    status: "ready",
    color: "#E37400",
    mark: "GA4",
  },
  {
    id: "metabase",
    name: "Metabase",
    description: "BI dashboards on call performance exports.",
    category: "Analytics",
    status: "ready",
    color: "#509EE3",
  },
  {
    id: "powerbi",
    name: "Power BI",
    description: "Enterprise embedding with Microsoft capacity.",
    category: "Analytics",
    status: "enterprise",
    color: "#F2C811",
    mark: "PBI",
  },
];

export const integrationStats = {
  total: integrations.length,
  ready: integrations.filter((i) => i.status === "ready").length,
  enterprise: integrations.filter((i) => i.status === "enterprise").length,
} as const;

export function integrationMark(item: Integration): string {
  if (item.mark) return item.mark;
  const parts = item.name.split(/\s+/);
  if (parts.length === 1) return item.name.slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[1][0]).toUpperCase();
}
